<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:34:22
?>
<h1>event</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
  <th>Distance</th>
</tr>
</thead>
<tbody>
<?php foreach ($events as $event): ?>
<tr>
    <td><?php echo link_to($event->getId(), 'event/show?id='.$event->getId()) ?></td>
      <td><?php echo $event->getName() ?></td>
      <td><?php echo $event->getDistance() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'event/create') ?>
