<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:34:22
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $event->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $event->getName() ?></td>
</tr>
<tr>
<th>Distance: </th>
<td><?php echo $event->getDistance() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'event/edit?id='.$event->getId()) ?>
&nbsp;<?php echo link_to('list', 'event/list') ?>
