<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:27:12
?>
<?php

/**
 * team actions.
 *
 * @package    sf_sandbox
 * @subpackage team
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 2288 2006-10-02 15:22:13Z fabien $
 */
class teamActions extends sfActions
{
  public function executeIndex ()
  {
    return $this->forward('team', 'list');
  }

  public function executeList ()
  {
    $this->teams = TeamPeer::doSelect(new Criteria());
  }

  public function executeShow ()
  {
    $this->team = TeamPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->team);
  }

  public function executeCreate ()
  {
    $this->team = new Team();

    $this->setTemplate('edit');
  }

  public function executeEdit ()
  {
    $this->team = TeamPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->team);
  }

  public function executeUpdate ()
  {
    if (!$this->getRequestParameter('id', 0))
    {
      $team = new Team();
    }
    else
    {
      $team = TeamPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($team);
    }

    $team->setId($this->getRequestParameter('id'));
    $team->setName($this->getRequestParameter('name'));
    $team->setShortname($this->getRequestParameter('shortname'));

    $team->save();

    return $this->redirect('team/show?id='.$team->getId());
  }

  public function executeDelete ()
  {
    $team = TeamPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($team);

    $team->delete();

    return $this->redirect('team/list');
  }
}
