<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:34:16
?>
<h1>meet</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
  <th>Startdate</th>
  <th>Enddate</th>
</tr>
</thead>
<tbody>
<?php foreach ($meets as $meet): ?>
<tr>
    <td><?php echo link_to($meet->getId(), 'meet/show?id='.$meet->getId()) ?></td>
      <td><?php echo $meet->getName() ?></td>
      <td><?php echo $meet->getStartdate() ?></td>
      <td><?php echo $meet->getEnddate() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'meet/create') ?>
