<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:15:22
?>
<?php use_helper('Object') ?>

<?php echo form_tag('swimmer/update') ?>

<?php echo object_input_hidden_tag($swimmer, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($swimmer, 'getName', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Year:</th>
  <td><?php echo object_input_tag($swimmer, 'getYear', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Team:</th>
  <td><?php echo object_select_tag($swimmer, 'getTeamId', array (
  'related_class' => 'Team',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($swimmer->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'swimmer/delete?id='.$swimmer->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'swimmer/show?id='.$swimmer->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'swimmer/list') ?>
<?php endif; ?>
</form>
