<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:27:12
?>
<?php use_helper('Object') ?>

<?php echo form_tag('team/update') ?>

<?php echo object_input_hidden_tag($team, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($team, 'getName', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Shortname:</th>
  <td><?php echo object_input_tag($team, 'getShortname', array (
  'size' => 20,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($team->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'team/delete?id='.$team->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'team/show?id='.$team->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'team/list') ?>
<?php endif; ?>
</form>
