<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:27:12
?>
<h1>team</h1>

<table>
<thead>
<tr>
  <th>Team Name</th>
</tr>
</thead>
<tbody>
<?php foreach ($teams as $team): ?>
<tr>
    <td><?php echo link_to($team->getName(), 'team/show?id='.$team->getId()) ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'team/create') ?>
