<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:27:12
?>
<h2><?php echo $team ?></h2>
<hr />
<?php echo link_to('edit', 'team/edit?id='.$team->getId()) ?>
&nbsp;<?php echo link_to('list', 'team/list') ?>
<hr />
<h3>Team Members</h3>
<table>
<?php if(sizeof($members) > 0) : ?>
<?php foreach($members as $member) : ?>
<tr>
  <td>
    <?php echo link_to($member, 'swimmer/show?id='.$member->getId()) ?>
  </td>
<?php endforeach ?>
</table>
<?php else : ?>
<p>There are no team members on this team.</p>
<?php endif ?>
