<?php
// auto-generated by sfPropelCrud
// date: 2006/12/01 20:07:07
?>
<?php use_helper('Object') ?>

<?php echo form_tag('split/update') ?>

<?php echo object_input_hidden_tag($split, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Time:</th>
  <td><?php echo object_select_tag($split, 'getTimeId', array (
  'related_class' => 'Time',
)) ?></td>
</tr>
<tr>
  <th>Number:</th>
  <td><?php echo object_input_tag($split, 'getNumber', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Duration:</th>
  <td><?php echo object_input_tag($split, 'getDuration', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Swimmer:</th>
  <td><?php echo object_select_tag($split, 'getSwimmerId', array (
  'related_class' => 'Swimmer',
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($split->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'split/delete?id='.$split->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'split/show?id='.$split->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'split/list') ?>
<?php endif; ?>
</form>
