<?php
// auto-generated by sfPropelCrud
// date: 2006/12/01 20:07:07
?>
<h1>split</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Time</th>
  <th>Number</th>
  <th>Duration</th>
  <th>Swimmer</th>
</tr>
</thead>
<tbody>
<?php foreach ($splits as $split): ?>
<tr>
    <td><?php echo link_to($split->getId(), 'split/show?id='.$split->getId()) ?></td>
      <td><?php echo $split->getTimeId() ?></td>
      <td><?php echo $split->getNumber() ?></td>
      <td><?php echo $split->getDuration() ?></td>
      <td><?php echo $split->getSwimmerId() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'split/create') ?>
