<?php
// auto-generated by sfPropelCrud
// date: 2006/12/01 20:07:07
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $split->getId() ?></td>
</tr>
<tr>
<th>Time: </th>
<td><?php echo $split->getTimeId() ?></td>
</tr>
<tr>
<th>Number: </th>
<td><?php echo $split->getNumber() ?></td>
</tr>
<tr>
<th>Duration: </th>
<td><?php echo $split->getDuration() ?></td>
</tr>
<tr>
<th>Swimmer: </th>
<td><?php echo $split->getSwimmerId() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'split/edit?id='.$split->getId()) ?>
&nbsp;<?php echo link_to('list', 'split/list') ?>
