<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:15:22
?>
<h1>swimmer</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
  <th>Year</th>
  <th>Team</th>
</tr>
</thead>
<tbody>
<?php foreach ($swimmers as $swimmer): ?>
<tr>
    <td><?php echo link_to($swimmer->getId(), 'swimmer/show?id='.$swimmer->getId()) ?></td>
      <td><?php echo $swimmer->getName() ?></td>
      <td><?php echo $swimmer->getYear() ?></td>
      <td><?php echo $swimmer->getTeamId() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'swimmer/create') ?>
