generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Split
    theme:            default

    fields:
      duration: { name: Split Time }
      number: { name: Split number }
      lane: { name: Lane }
      swimmer_id: { name: Swimmer }
      
