<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:34:16
?>
<?php use_helper('Object') ?>

<?php echo form_tag('meet/update') ?>

<?php echo object_input_hidden_tag($meet, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($meet, 'getName', array (
  'size' => 20,
)) ?></td>
</tr>
<tr>
  <th>Startdate:</th>
  <td><?php echo object_input_date_tag($meet, 'getStartdate', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
<tr>
  <th>Enddate:</th>
  <td><?php echo object_input_date_tag($meet, 'getEnddate', array (
  'rich' => true,
  'withtime' => true,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($meet->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'meet/delete?id='.$meet->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'meet/show?id='.$meet->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'meet/list') ?>
<?php endif; ?>
</form>
