<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:34:16
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $meet->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $meet->getName() ?></td>
</tr>
<tr>
<th>Startdate: </th>
<td><?php echo $meet->getStartdate() ?></td>
</tr>
<tr>
<th>Enddate: </th>
<td><?php echo $meet->getEnddate() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'meet/edit?id='.$meet->getId()) ?>
&nbsp;<?php echo link_to('list', 'meet/list') ?>
