<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2006/12/16 12:44:04

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'sqlite://./../data/sandbox.db',
), 'propel');
$this->databases['propel'] = $database;
