<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:34:01
?>
<?php use_helper('Object') ?>

<?php echo form_tag('time/update') ?>

<?php echo object_input_hidden_tag($time, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Swimmer:</th>
  <td><?php echo object_select_tag($time, 'getSwimmerId', array (
  'related_class' => 'Swimmer',
)) ?></td>
</tr>
<tr>
  <th>Meet:</th>
  <td><?php echo object_select_tag($time, 'getMeetId', array (
  'related_class' => 'Meet',
)) ?></td>
</tr>
<tr>
  <th>Event:</th>
  <td><?php echo object_select_tag($time, 'getEventId', array (
  'related_class' => 'Event',
)) ?></td>
</tr>
<tr>
  <th>Time:</th>
  <td><?php echo object_input_tag($time, 'getTime', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Place:</th>
  <td><?php echo object_input_tag($time, 'getPlace', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Lane:</th>
  <td><?php echo object_input_tag($time, 'getLane', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($time->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'time/delete?id='.$time->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'time/show?id='.$time->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'time/list') ?>
<?php endif; ?>
</form>
