<?php
// auto-generated by sfPropelCrud
// date: 2006/12/01 20:07:36
?>
<h1>time</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Meet</th>
  <th>Event</th>
  <th>Time</th>
  <th>Place</th>
  <th>Lane</th>
</tr>
</thead>
<tbody>
<?php foreach ($times as $time): ?>
<tr>
    <td><?php echo link_to($time->getId(), 'time/show?id='.$time->getId()) ?></td>
      <td><?php echo $time->getMeetId() ?></td>
      <td><?php echo $time->getEventId() ?></td>
      <td><?php echo $time->getTime() ?></td>
      <td><?php echo $time->getPlace() ?></td>
      <td><?php echo $time->getLane() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'time/create') ?>
