<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:34:01
?>
<h1>time</h1>

<table>
<thead>
<tr>
  <th></th>
  <th>Swimmer</th>
  <th>Meet</th>
  <th>Event</th>
  <th>Time</th>
  <th>Place</th>
  <th>Lane</th>
</tr>
</thead>
<tbody>
<?php foreach ($times as $time): ?>
<tr>
    <td><?php echo link_to('e', 'time/show?id='.$time->getId()) ?></td>
      <td><?php echo link_to($time->getSwimmer(), 'swimmer/show?id='.$time->getSwimmerId()) ?></td>
      <td><?php echo link_to($time->getMeet(), 'meet/show?id='.$time->getMeetId()) ?></td>
      <td><?php echo link_to($time->getEvent(), 'event/show?id='.$time->getEventId()) ?></td>
      <td><?php echo $time->getTime() ?></td>
      <td><?php echo $time->getPlace() ?></td>
      <td><?php echo $time->getLane() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'time/create') ?>
