<?php
// auto-generated by sfPropelCrud
// date: 2006/12/17 12:51:37
?>
<h1>team</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Name</th>
  <th>Shortname</th>
</tr>
</thead>
<tbody>
<?php foreach ($teams as $team): ?>
<tr>
    <td><?php echo link_to($team->getId(), 'team/show?id='.$team->getId()) ?></td>
      <td><?php echo $team->getName() ?></td>
      <td><?php echo $team->getShortname() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'team/create') ?>
