<?php
// auto-generated by sfPropelCrud
// date: 2006/12/17 12:51:37
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $team->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $team->getName() ?></td>
</tr>
<tr>
<th>Shortname: </th>
<td><?php echo $team->getShortname() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'team/edit?id='.$team->getId()) ?>
&nbsp;<?php echo link_to('list', 'team/list') ?>
