<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:34:16
?>
<?php

/**
 * meet actions.
 *
 * @package    sf_sandbox
 * @subpackage meet
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 2288 2006-10-02 15:22:13Z fabien $
 */
class meetActions extends sfActions
{
  public function executeIndex ()
  {
    return $this->forward('meet', 'list');
  }

  public function executeList ()
  {
    $this->meets = MeetPeer::doSelect(new Criteria());
  }

  public function executeShow ()
  {
    $this->meet = MeetPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->meet);
  }

  public function executeCreate ()
  {
    $this->meet = new Meet();

    $this->setTemplate('edit');
  }

  public function executeEdit ()
  {
    $this->meet = MeetPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->meet);
  }

  public function executeUpdate ()
  {
    if (!$this->getRequestParameter('id', 0))
    {
      $meet = new Meet();
    }
    else
    {
      $meet = MeetPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($meet);
    }

    $meet->setId($this->getRequestParameter('id'));
    $meet->setName($this->getRequestParameter('name'));
    if ($this->getRequestParameter('startdate'))
    {
      list($d, $m, $y) = sfI18N::getDateForCulture($this->getRequestParameter('startdate'), $this->getUser()->getCulture());
      $meet->setStartdate("$y-$m-$d");
    }
    if ($this->getRequestParameter('enddate'))
    {
      list($d, $m, $y) = sfI18N::getDateForCulture($this->getRequestParameter('enddate'), $this->getUser()->getCulture());
      $meet->setEnddate("$y-$m-$d");
    }

    $meet->save();

    return $this->redirect('meet/show?id='.$meet->getId());
  }

  public function executeDelete ()
  {
    $meet = MeetPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($meet);

    $meet->delete();

    return $this->redirect('meet/list');
  }
}
