<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2006/12/16 12:44:04
sfConfig::add(array(
  'sf_i18n_default_culture' => 'en',
  'sf_i18n_source' => 'XLIFF',
  'sf_i18n_debug' => false,
  'sf_i18n_cache' => true,
  'sf_i18n_untranslated_prefix_0' => 'T',
  'sf_i18n_untranslated_suffix_0' => '/T',
));
