<?php
// auto-generated by sfPropelCrud
// date: 2006/11/29 13:34:01
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $time->getId() ?></td>
</tr>
<tr>
<th>Swimmer: </th>
<td><?php echo $time->getSwimmerId() ?></td>
</tr>
<tr>
<th>Meet: </th>
<td><?php echo $time->getMeetId() ?></td>
</tr>
<tr>
<th>Event: </th>
<td><?php echo $time->getEventId() ?></td>
</tr>
<tr>
<th>Time: </th>
<td><?php echo $time->getTime() ?></td>
</tr>
<tr>
<th>Place: </th>
<td><?php echo $time->getPlace() ?></td>
</tr>
<tr>
<th>Lane: </th>
<td><?php echo $time->getLane() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'time/edit?id='.$time->getId()) ?>
&nbsp;<?php echo link_to('list', 'time/list') ?>
