<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2006/12/16 12:44:13
sfConfig::add(array(
  'sf_logging_enabled' => true,
  'sf_logging_level' => 'debug',
  'sf_logging_rotate' => false,
  'sf_logging_period' => 7,
  'sf_logging_history' => 10,
  'sf_logging_purge' => true,
));
