<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2006/12/16 12:48:27
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
